/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.ulbra.view;

import br.ulbra.controller.FornecedorController;
import br.ulbra.model.Fornecedor;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author aluno.saolucas
 */
public class FornecedorView extends javax.swing.JFrame {

    /**
     * Creates new form FornecedorView
     */
     public FornecedorView() {
        initComponents();
        controller = new FornecedorController();
        this.setLocationRelativeTo(null);
        initTableModel();
        atualizarTabela();  
    }
   
    private void limparCampos(){
        txtidFor.setText("");
        txtNomeRazao.setText("");
        txtNomeFantasia.setText("");
        txtTelefoneFor.setText("");
        txtEmailFor.setText("");
        DefaultTableModel model = (DefaultTableModel) tblFornecedor.getModel();
        model.setRowCount(0);  // apaga todas as linhas;
    }
    private FornecedorController controller;
   
    private void atualizarTabela(){
         try {
            DefaultTableModel modelTbl = (DefaultTableModel) tblFornecedor.getModel();
            modelTbl.setRowCount(0);
            List<Fornecedor> lista = controller.listar();
            for (Fornecedor u : lista) {
                modelTbl.addRow(new Object[]{u.getIdFor(), u.getNomeRazao(), u.getNomeFantasia(), u.getTelefone(), u.getEmail()});
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "erro ao listar:" + ex.getMessage());
        }
    }
   
    public void setBotoes(int op){
        switch(op){
            case 1:btnSalvarFor.setEnabled(false);
                btnExcluirFor.setEnabled(true);
                btnEditarFor.setEnabled(true);
                break;
            default:
                btnSalvarFor.setEnabled(true);
                btnExcluirFor.setEnabled(false);
                btnEditarFor.setEnabled(false);
        }
    }

        private void initTableModel() {
        javax.swing.table.DefaultTableModel model = new javax.swing.table.DefaultTableModel(
                new Object[][]{},
                new String[]{"id", "nome", "email", "telefone"}) {
            @Override
            public boolean isCellEditable(int row, int col) {
                return false;
            }
        };
        tblFornecedor.setModel(model);
    }                            
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtidFor = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNomeRazao = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtNomeFantasia = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtTelefoneFor = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtEmailFor = new javax.swing.JTextField();
        btnSalvarFor = new javax.swing.JButton();
        btnLimparFor = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblFornecedor = new javax.swing.JTable();
        btnEditarFor = new javax.swing.JButton();
        btnExcluirFor = new javax.swing.JButton();
        btnListarFor = new javax.swing.JButton();

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("id");

        txtidFor.setBackground(new java.awt.Color(255, 255, 255));
        txtidFor.setForeground(new java.awt.Color(0, 0, 0));

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Nome (Razao)");

        txtNomeRazao.setBackground(new java.awt.Color(255, 255, 255));
        txtNomeRazao.setForeground(new java.awt.Color(0, 0, 0));

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Nome (Fantasia)");

        txtNomeFantasia.setBackground(new java.awt.Color(255, 255, 255));
        txtNomeFantasia.setForeground(new java.awt.Color(0, 0, 0));

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Telefone");

        txtTelefoneFor.setBackground(new java.awt.Color(255, 255, 255));
        txtTelefoneFor.setForeground(new java.awt.Color(0, 0, 0));

        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Email");

        txtEmailFor.setBackground(new java.awt.Color(255, 255, 255));
        txtEmailFor.setForeground(new java.awt.Color(0, 0, 0));

        btnSalvarFor.setText("Salvar");
        btnSalvarFor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarForActionPerformed(evt);
            }
        });

        btnLimparFor.setText("Limpar");
        btnLimparFor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparForActionPerformed(evt);
            }
        });

        tblFornecedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Id", "Nome Razao", "Nome Fantasia", "Telefone", "Email"
            }
        ));
        jScrollPane1.setViewportView(tblFornecedor);

        btnEditarFor.setText("Editar");
        btnEditarFor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarForActionPerformed(evt);
            }
        });

        btnExcluirFor.setText("Excluir");

        btnListarFor.setText("Listar");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnSalvarFor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                        .addComponent(btnLimparFor)
                        .addGap(29, 29, 29))
                    .addComponent(txtNomeFantasia)
                    .addComponent(txtTelefoneFor)
                    .addComponent(txtEmailFor)
                    .addComponent(txtNomeRazao)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(txtidFor, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(btnEditarFor)
                        .addGap(18, 18, 18)
                        .addComponent(btnExcluirFor)
                        .addGap(18, 18, 18)
                        .addComponent(btnListarFor)))
                .addGap(46, 46, 46))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtidFor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(txtNomeRazao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(btnEditarFor)
                    .addComponent(btnExcluirFor)
                    .addComponent(btnListarFor))
                .addGap(18, 18, 18)
                .addComponent(txtNomeFantasia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtTelefoneFor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEmailFor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvarFor)
                    .addComponent(btnLimparFor))
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarForActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarForActionPerformed
         try{
            String nomeRazao = txtNomeRazao.getText().trim();
            String nomeFantasia = txtNomeFantasia.getText().trim();
            String telefone = txtTelefoneFor.getText().trim();
            String email = txtEmailFor.getText().trim();
            if(nomeRazao.isEmpty()){
                javax.swing.JOptionPane.showMessageDialog(this, "Nome é obrigatório");
                return;
            }
            Fornecedor f = new Fornecedor(0, nomeRazao, nomeFantasia, telefone, email);
            controller.salvar(f);
            javax.swing.JOptionPane.showMessageDialog(this, "Fornecedor salvo (ID=" + f.getIdFor() + ")");
            atualizarTabela();
            limparCampos();
        } catch (Exception ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "Erro ao salvar: " + ex.getMessage());

        }
    }//GEN-LAST:event_btnSalvarForActionPerformed

    private void btnLimparForActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparForActionPerformed
       txtidFor.setText(null);
       txtNomeRazao.setText(null);
       txtNomeFantasia.setText(null);
       txtEmailFor.setText(null);
       txtTelefoneFor.setText(null);
    }//GEN-LAST:event_btnLimparForActionPerformed

    private void btnEditarForActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarForActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditarForActionPerformed

   
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FornecedorView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FornecedorView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FornecedorView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FornecedorView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FornecedorView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditarFor;
    private javax.swing.JButton btnExcluirFor;
    private javax.swing.JButton btnLimparFor;
    private javax.swing.JButton btnListarFor;
    private javax.swing.JButton btnSalvarFor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblFornecedor;
    private javax.swing.JTextField txtEmailFor;
    private javax.swing.JTextField txtNomeFantasia;
    private javax.swing.JTextField txtNomeRazao;
    private javax.swing.JTextField txtTelefoneFor;
    private javax.swing.JTextField txtidFor;
    // End of variables declaration//GEN-END:variables
}
