/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.ulbra.view;

import br.ulbra.controller.UsuarioController;
import br.ulbra.model.Usuario;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author aluno.saolucas
 */
public class UsuarioView extends javax.swing.JFrame {
    private Usuario usuarioLogado;

    private UsuarioController controller; // aqui deve ser UsuarioController

    /**
     * Creates new form UsuarioView
     */
    public UsuarioView() {
        initComponents();
        controller = new UsuarioController();
        atualizarTabelaUsuarios();
    }

    public UsuarioView(Usuario usuarioLogado) {
        this.usuarioLogado = usuarioLogado;
        initComponents();
    }
  

    private void atualizarTabelaUsuarios() {
        try {
            DefaultTableModel modelo = (DefaultTableModel) TblUsuario.getModel();
            modelo.setRowCount(0); // limpa tabela antes de preencher

            List<Usuario> lista = controller.listar();

            for (Usuario u : lista) {
                modelo.addRow(new Object[]{
                    u.getId(),
                    u.getNome(),
                    u.getLogin(),
                    u.isAtivo()
                });
            }
        } catch (Exception ex) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Erro ao atualizar tabela: " + ex.getMessage());
        }
    }

    private void limparCamposUsuario() {
        TxtIdUsu.setText("");
        TxtNomeUsu.setText("");
        TxtLoginUsu.setText("");
        TxtSenhaUsu.setText("");
        ChkAtivoUsu.setSelected(false);

        TxtNomeUsu.requestFocus(); // volta o cursor pro campo nome
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        TxtIdUsu = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        TxtNomeUsu = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        TxtLoginUsu = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        TxtSenhaUsu = new javax.swing.JTextField();
        ChkAtivoUsu = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TblUsuario = new javax.swing.JTable();
        BtnSalvarUsu = new javax.swing.JButton();
        BtnAlterarUsu = new javax.swing.JButton();
        BtnExcluirUsu = new javax.swing.JButton();
        BtnListarUsu = new javax.swing.JButton();
        BtnLimparUsu = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel1.setText("ID");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setText("Nome");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setText("Login");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4.setText("Senha");

        ChkAtivoUsu.setBackground(new java.awt.Color(0, 0, 0));
        ChkAtivoUsu.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        ChkAtivoUsu.setForeground(new java.awt.Color(51, 51, 51));
        ChkAtivoUsu.setText("Ativo");

        TblUsuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Nome", "Login", "Ativo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TblUsuario);

        BtnSalvarUsu.setText("SALVAR");
        BtnSalvarUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSalvarUsuActionPerformed(evt);
            }
        });

        BtnAlterarUsu.setText("ALTERAR");
        BtnAlterarUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAlterarUsuActionPerformed(evt);
            }
        });

        BtnExcluirUsu.setText("EXCLUIR");
        BtnExcluirUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnExcluirUsuActionPerformed(evt);
            }
        });

        BtnListarUsu.setText("LISTAR");
        BtnListarUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnListarUsuActionPerformed(evt);
            }
        });

        BtnLimparUsu.setText("LIMPAR");
        BtnLimparUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLimparUsuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ChkAtivoUsu)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(TxtLoginUsu)
                        .addComponent(jLabel4)
                        .addComponent(jLabel3)
                        .addComponent(jLabel2)
                        .addComponent(TxtNomeUsu)
                        .addComponent(TxtSenhaUsu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 485, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(BtnSalvarUsu)
                                .addGap(18, 18, 18)
                                .addComponent(BtnAlterarUsu)
                                .addGap(18, 18, 18)
                                .addComponent(BtnExcluirUsu)
                                .addGap(18, 18, 18)
                                .addComponent(BtnListarUsu)
                                .addGap(18, 18, 18)
                                .addComponent(BtnLimparUsu))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(TxtIdUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel1))
                            .addGap(172, 172, 172)
                            .addComponent(jLabel5))))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxtIdUsu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxtNomeUsu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxtLoginUsu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxtSenhaUsu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ChkAtivoUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnSalvarUsu)
                    .addComponent(BtnAlterarUsu)
                    .addComponent(BtnExcluirUsu)
                    .addComponent(BtnListarUsu)
                    .addComponent(BtnLimparUsu))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnSalvarUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSalvarUsuActionPerformed
        try {
            String nome = TxtNomeUsu.getText().trim();
            String login = TxtLoginUsu.getText().trim();
            String senha = TxtSenhaUsu.getText().trim();
            boolean ativo = ChkAtivoUsu.isSelected();

            if (nome.isEmpty() || login.isEmpty() || senha.isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(this,
                        "Nome, Login e Senha são obrigatórios!");
                return;
            }

            Usuario u = new Usuario(0, nome, login, senha, ativo);
            controller.salvar(u);

            javax.swing.JOptionPane.showMessageDialog(this,
                    "Usuário salvo com ID: " + u.getId());

            atualizarTabelaUsuarios();
            limparCamposUsuario();

        } catch (Exception ex) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Erro ao salvar usuário: " + ex.getMessage());
        }


    }//GEN-LAST:event_BtnSalvarUsuActionPerformed

    private void BtnAlterarUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAlterarUsuActionPerformed
        try {
            // Tenta obter o ID pelo campo; se vazio, tenta pela tabela
            Integer id = null;
            String idCampo = TxtIdUsu.getText().trim();
            if (!idCampo.isEmpty()) {
                try {
                    id = Integer.parseInt(idCampo);
                } catch (NumberFormatException e) {
                    javax.swing.JOptionPane.showMessageDialog(this, "ID inválido no campo ID.");
                    return;
                }
            } else {
                int linha = TblUsuario.getSelectedRow();
                if (linha >= 0) {
                    try {
                        id = Integer.parseInt(TblUsuario.getValueAt(linha, 0).toString());
                        TxtIdUsu.setText(String.valueOf(id)); // opcional: refletir no campo
                    } catch (NumberFormatException e) {
                        javax.swing.JOptionPane.showMessageDialog(this, "ID inválido na tabela.");
                        return;
                    }
                }
            }

            if (id == null || id <= 0) {
                javax.swing.JOptionPane.showMessageDialog(this, "Selecione um usuário na tabela ou informe um ID válido para alterar.");
                return;
            }

            String nome = TxtNomeUsu.getText().trim();
            String login = TxtLoginUsu.getText().trim();
            String senha = TxtSenhaUsu.getText().trim();
            boolean ativo = ChkAtivoUsu.isSelected();

            if (nome.isEmpty() || login.isEmpty() || senha.isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(this, "Nome, Login e Senha são obrigatórios!");
                return;
            }

            Usuario u = new Usuario(id, nome, login, senha, ativo);
            controller.atualizar(u);

            javax.swing.JOptionPane.showMessageDialog(this, "Usuário atualizado com sucesso!");
            atualizarTabelaUsuarios();
            limparCamposUsuario();
        } catch (Exception ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "Erro ao alterar usuário: " + ex.getMessage());
        }    }//GEN-LAST:event_BtnAlterarUsuActionPerformed

    private void BtnListarUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnListarUsuActionPerformed
        atualizarTabelaUsuarios();
    }//GEN-LAST:event_BtnListarUsuActionPerformed

    private void BtnExcluirUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnExcluirUsuActionPerformed
        int linhaSelecionada = TblUsuario.getSelectedRow();

        if (linhaSelecionada == -1) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Selecione um usuário para excluir!");
            return;
        }

        int confirm = javax.swing.JOptionPane.showConfirmDialog(this,
                "Tem certeza que deseja excluir este usuário?",
                "Confirmação",
                javax.swing.JOptionPane.YES_NO_OPTION);

        if (confirm != javax.swing.JOptionPane.YES_OPTION) {
            return;
        }

        try {
            int id = Integer.parseInt(TblUsuario.getValueAt(linhaSelecionada, 0).toString());
            controller.excluir(id); // Seu controller deve ter um método excluir(int id)
            javax.swing.JOptionPane.showMessageDialog(this, "Usuário excluído com sucesso!");

            atualizarTabelaUsuarios();
            limparCamposUsuario();
        } catch (Exception ex) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Erro ao excluir usuário: " + ex.getMessage());
        }    }//GEN-LAST:event_BtnExcluirUsuActionPerformed

    private void BtnLimparUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLimparUsuActionPerformed
        try {
            limparCamposUsuario();
            // opcional: limpar seleção da tabela
            TblUsuario.clearSelection();
        } catch (Exception ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "Erro ao limpar: " + ex.getMessage());
        }    }//GEN-LAST:event_BtnLimparUsuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UsuarioView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UsuarioView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UsuarioView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UsuarioView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UsuarioView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAlterarUsu;
    private javax.swing.JButton BtnExcluirUsu;
    private javax.swing.JButton BtnLimparUsu;
    private javax.swing.JButton BtnListarUsu;
    private javax.swing.JButton BtnSalvarUsu;
    private javax.swing.JRadioButton ChkAtivoUsu;
    private javax.swing.JTable TblUsuario;
    private javax.swing.JTextField TxtIdUsu;
    private javax.swing.JTextField TxtLoginUsu;
    private javax.swing.JTextField TxtNomeUsu;
    private javax.swing.JTextField TxtSenhaUsu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
