package br.ulbra.view;

import br.ulbra.model.Usuario;

/**
 *
 * @author aluno.saolucas
 */
public class MenuPrincipalView extends javax.swing.JFrame {

   private final Usuario usuarioLogado;

    public MenuPrincipalView(Usuario usuarioLogado) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.usuarioLogado = usuarioLogado;
        configurarUsuario();
    }

    private void configurarUsuario() {
        setTitle("CRUD - Logado como: " + usuarioLogado.getNome() + " (" + usuarioLogado.getLogin() + ")");
        boolean podeGerenciarUsuarios = "admin".equalsIgnoreCase(usuarioLogado.getLogin());
        itemUsuario.setEnabled(podeGerenciarUsuarios);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        itemUsuario = new javax.swing.JMenuBar();
        MnCadastro = new javax.swing.JMenu();
        MnClientes = new javax.swing.JMenuItem();
        MnUsuarios = new javax.swing.JMenuItem();
        MnSobre = new javax.swing.JMenu();
        MnSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 898, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 506, Short.MAX_VALUE)
        );

        itemUsuario.setBackground(new java.awt.Color(255, 255, 255));

        MnCadastro.setText("Cadastros");
        MnCadastro.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        MnClientes.setText("Clientes");
        MnClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnClientesActionPerformed(evt);
            }
        });
        MnCadastro.add(MnClientes);

        MnUsuarios.setText("Usuários");
        MnUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnUsuariosActionPerformed(evt);
            }
        });
        MnCadastro.add(MnUsuarios);

        itemUsuario.add(MnCadastro);

        MnSobre.setText("Sobre");
        MnSobre.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        MnSair.setText("Sair");
        MnSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MnSairMouseClicked(evt);
            }
        });
        MnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnSairActionPerformed(evt);
            }
        });
        MnSobre.add(MnSair);

        itemUsuario.add(MnSobre);

        setJMenuBar(itemUsuario);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MnSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MnSairMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_MnSairMouseClicked

    private void MnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnSairActionPerformed
dispose();
    }//GEN-LAST:event_MnSairActionPerformed

    private void MnClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnClientesActionPerformed
        new ClienteView(usuarioLogado).setVisible(true);
    }//GEN-LAST:event_MnClientesActionPerformed

    private void MnUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnUsuariosActionPerformed
        new UsuarioView(usuarioLogado).setVisible(true);
    }//GEN-LAST:event_MnUsuariosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MnCadastro;
    private javax.swing.JMenuItem MnClientes;
    private javax.swing.JMenuItem MnSair;
    private javax.swing.JMenu MnSobre;
    private javax.swing.JMenuItem MnUsuarios;
    private javax.swing.JMenuBar itemUsuario;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
